# Generated by Django 4.1 on 2025-02-03 19:00

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_moviesession_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='movie_image',
            field=models.ImageField(null=True, upload_to=cinema.models.movie_session_image_path),
        ),
    ]
